print("¡Hola! Aqui puedes realizar sumas")
numero1 = input("Por favor ingrese el primer valor: ")
numero2 = input("Por favor ingrese el segundo valor: ")
numero1 = int(numero1)
numero2 = int(numero2)
print(numero1, "+", numero2, "=", numero1 + numero2)